# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Stock": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pankaj-kvhld.github.io/intel_invest/"

git_url = "https://github.com/pankaj-kvhld/intel_invest/tree/master/"

def custom_doc_links(name): return None
